services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zenran
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/zenran
      JWT_ACCESS_SECRET: supersecretdev
      JWT_REFRESH_SECRET: superrefresh
    ports:
      - "3000:3000"
volumes:
  db_data:
